info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 首页
  /user:
    get:
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      tags:
      - 用户
swagger: "2.0"
